[package]
name = "servify"
version = "0.1.0"
authors = ["Juan Eugenio Abadie <juaneabadie@gmail.com>"]
edition = "2018"

[dependencies]
rustless = "0.10.0"
hyper = "0.10.5"
rustc-serialize = "0.3"
valico = "1"

[dependencies.iron]
version = "*"
