[package]
name = "servify"
version = "0.1.0"
authors = ["Juan Eugenio Abadie <juaneabadie@gmail.com>"]

[dependencies]
rustless = "0.10.0"
clap = { git = "https://github.com/clap-rs/clap" }
jsonway = "1"
tempfile = "3"
base64 = "0.11.0"

[dependencies.iron]
version = "0.4.0"
